# Generated by Django 4.2.3 on 2023-07-26 14:42

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.CharField(blank=True, max_length=75, null=True)),
                ('tumbnail', models.ImageField(upload_to='category')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateField(auto_now=True, verbose_name='Date Updated')),
                ('children', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='child', to='core.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', editable=False, length=10, max_length=10, prefix='', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateField(auto_now_add=True, verbose_name='Date Updated')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='category', to='core.category')),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='core.productimage')),
            ],
        ),
    ]
