# Generated by Django 5.0.2 on 2024-03-02 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product/<django.db.models.query_utils.DeferredAttribute object at 0x7fd138bd25d0>/<django.db.models.query_utils.DeferredAttribute object at 0x7fd138bd3950>'),
        ),
    ]
