# Generated by Django 5.0.2 on 2024-03-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product/<django.db.models.query_utils.DeferredAttribute object at 0x7f6415321220>/<django.db.models.query_utils.DeferredAttribute object at 0x7f64153a3200>'),
        ),
    ]
