# Generated by Django 5.0.2 on 2024-03-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_product_image_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product/<django.db.models.query_utils.DeferredAttribute object at 0x7efdb5f00680>/<django.db.models.query_utils.DeferredAttribute object at 0x7efdb5edb590>'),
        ),
    ]
