# Generated by Django 5.0.2 on 2024-03-04 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pages',
            new_name='Page',
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name_plural': 'Page'},
        ),
    ]
