# Generated by Django 5.0.2 on 2024-03-04 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_rename_pages_page_alter_page_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name_plural': 'Pages'},
        ),
    ]
